format = """
$username\
$hostname\
$directory\
${custom.devbox}\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$golang\
$rust\
$zig\
$vagrant\
$container\
$cmd_duration\
$jobs\
$time\
$line_break\
$character"""

add_newline = false

[username]
show_always = true
style_user = "bold purple"
# in nushell the first character "|" does not set it's color to "bold white", but to green for some reason
# so had to specify that here, maybe it's a porblem with the config on nu
format = '[|](bold white)[$user]($style)[@](bold green)' 

[hostname]
ssh_only = false
style = "bold blue"
format = '[$hostname]($style)'

[directory]
style = "bold yellow"
read_only = " ï ½"
truncation_length = 0 
truncate_to_repo = false
format= ':[$path]($style)[$read_only]($read_only_style)|'

[fill] #by default fill uses dots
symbol = " "

# for guix shell gonna propably use "â‹Ž" with bold yellow https://unicode-table.com/en/22CE/ or https://unicode-table.com/en/2648/ or â™ˆ

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vicmd_symbol = "[<](bold purple)"

[time]
disabled = false
style = "bold white"
format = '|[$time]($style)|'

[cmd_duration]
style = "bold yellow"
format = '|[â± $duration]($style)'

[aws]
format = '|[$symbol($profile)(\($region\))(\[$duration\])]($style)'

[bun]
format = '|[$symbol($version)]($style)'

[c]
format = '|[$symbol($version(-$name))]($style)'

[cmake]
format = '|[$symbol($version)]($style)'

[cobol]
format = '|[$symbol($version)]($style)'

[conda]
format = '|[$symbol$environment]($style)'

[crystal]
format = '|[$symbol($version)]($style)'

[daml]
format = '|[$symbol($version)]($style)'

[dart]
format = '|[$symbol($version)]($style)'

[deno]
format = '|[$symbol($version)]($style)'

[docker_context]
format = '|[$symbol$context]($style)'

[dotnet]
format = '|[$symbol($version)(ðŸŽ¯ $tfm)]($style)'

[elixir]
format = '|[$symbol($version \(OTP $otp_version\))]($style)'

[elm]
format = '|[$symbol($version)]($style)'

[erlang]
format = '|[$symbol($version)]($style)'

[gcloud]
format = '|[$symbol$account(@$domain)(\($region\))]($style)'

[git_branch]
format = '[$symbol$branch]($style)|'

[git_status]
format = '([$all_status$ahead_behind]($style)|)'

[golang]
format = '|[$symbol($version)]($style)'

[haskell]
format = '|[$symbol($version)]($style)'

[helm]
format = '|[$symbol($version)]($style)'

[hg_branch]
format = '|[$symbol$branch]($style)'

[java]
format = '|[$symbol($version)]($style)'

[julia]
format = '|[$symbol($version)]($style)'

[kotlin]
format = '|[$symbol($version)]($style)'

[kubernetes]
format = '|[$symbol$context( \($namespace\))]($style)'

[lua]
format = '|[$symbol($version)]($style)'

[memory_usage]
format = '|[$symbol[$ram( | $swap)]($style)'

[nim]
format = '|[$symbol($version)]($style)'

[nix_shell]
format = '|[$symbol$state( \($name\))]($style)'

[nodejs]
format = '|[$symbol($version)]($style)'

[ocaml]
format = '|[$symbol($version)(\($switch_indicator$switch_name\))]($style)'

[openstack]
format = '|[$symbol$cloud(\($project\))]($style)'

[package]
format = '|[$symbol$version]($style)'

[perl]
format = '|[$symbol($version)]($style)'

[php]
format = '|[$symbol($version)]($style)'

[pulumi]
format = '|[$symbol$stack]($style)'

[purescript]
format = '|[$symbol($version)]($style)'

[python]
format = '|[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[raku]
format = '|[$symbol($version-$vm_version)]($style)'

[red]
format = '|[$symbol($version)]($style)'

[ruby]
format = '|[$symbol($version)]($style)'

[rust]
format = '|[$symbol($version)]($style)'

[scala]
format = '|[$symbol($version)]($style)'

[spack]
format = '|[$symbol$environment]($style)'

[sudo]
format = '|[as $symbol]'

[swift]
format = '|[$symbol($version)]($style)'

[terraform]
format = '|[$symbol$workspace]($style)'

[vagrant]
format = '|[$symbol($version)]($style)'

[vlang]
format = '|[$symbol($version)]($style)'

[zig]
format = '|[$symbol($version)]($style)'

[custom.devbox]
format = "ðŸ“¦[devbox](blue bold)[|](bold white)"
when = """ test "$DEVBOX_SHELL_ENABLED" "==" "1" """
